### ISSUE TITLE
ItemInfo + ru

### ISSUE THREAD

**Issue by 4ikistik** [millworm/Csgo.tm-Bot#1]
Хотел поблагодарить за этот продукт, очень в помощь, спасибо.
Пример запроса:
https://market.csgo.com/api/ItemInfo/[classid]_[instanceid]/[language]/?key=[your_secret_key]
[language] — на каком языке получить описание предмета, возможные значения **ru** или **en**
Есть костыль с реализацией **ru**?

**Comment by millworm** [comment]
Честно говоря не знаю. Не использую описание предметов

**Comment by 4ikistik** [comment]
просто эта функция нужна для того, чтобы вносить предмет в список и дальнейшей работы с ним. спасибо за ответ.

**Comment by millworm** [comment]
покупать можно и без указания хеша предмета. он, кстати, довольно часто меняет у предметов

**Comment by millworm** [comment]
а для чего тебе хранить описание предмета?

**Comment by 4ikistik** [comment]
Использую сборку недавно и пока только для приема и передачи. Стал изучать покупки и т.д. и вот наткнулся на "камушек" решил отписать об этом. Меня интересует сам процесс хранения информации об предмете, кот. я планирую купить. Думаю же, что для этого нужно "хранить  описание предмета". Или есть другие способы для реализации покупки конкретного предмета?

**Comment by millworm** [comment]
я храню только название предмета, его classid и instanceid. раньше хранил хеш, который брался из этой(Iteminfo) функции, но потом хеш у предметов стал часто обновляться и перестал его использовать. для покупки нужны только classid и instanceid, хеш необязателен 
если прям так хочется хранить описание, то попробуй вот это
System.Text.RegularExpressions.Regex.Unescape(str)

**Comment by 4ikistik** [comment]
есть возможность назначать цену покупки для каждого предмета или эта функция ограничена значением price?

**Comment by millworm** [comment]
в этой версии только через price. он там еще скидку учитывает при выставлении цены

**Comment by 4ikistik** [comment]
ясн, ждем очередные версии, проект очень радует, молодца.
