### ISSUE TITLE
Itimer (таймер между вещами)

### ISSUE THREAD

**Issue by 4ikistik** [millworm/Csgo.tm-Bot#10]
Раньше можно было забрать только у одного бота, после у следующего, т.е. в реальном времени только у одного обмен.
В новой сборке сайт может создавать n количество обменов (лимит мне неизвестен).
Можно ли, чтобы бот просто создавал эти обмены без очереди, а там уже все зависит от стима конечно?
/сейчас передача в среднем 1 транш 2-4 минуты/

**Comment by 4ikistik** [comment]
Вдогонку: хорошо бы поместить в Program.cs команду bot.Dispose(); при нажатии клавиши "q" (давно пропала, сейчас отписал)
И очень интересна функция Finding, или это отголоски старого? 
спс за новую сборку, видно, что проделана работа, будем тестить.

**Comment by millworm** [comment]
да, там в планах на будущее есть проверка вещей на вывод после принятия обмена, но руки как-то не дойдут. вообще бот проверяет вещи на вывод в PingPongTimer раз в PingPongTimerTime секунд. по умолчанию это 30 секунд. можно пока уменьшить это время.
Finding это отголосок от старых версий, когда стоял вопрос как запускать проход по списку покупок - самому создавать поток или отдать все управление этим c# через Task
