### ISSUE TITLE
SetPrice 

### ISSUE THREAD

**Issue by 4ikistik** [millworm/Csgo.tm-Bot#2]
Есть в планах реализации выставления купленных предметов на сайт?

**Comment by millworm** [comment]
может как-нибудь потом. ну а пока, можно получать и передавать проданное(если mafile есть)

**Comment by 4ikistik** [comment]
SetPrice очень интересен в данном проекте, спс

**Comment by millworm** [comment]
если подскажите алгоритм выбора цен, то сделаю и setprice
и интерфейс сделаем, если надо

**Comment by 4ikistik** [comment]
_GetInv_ (Получение инвентаря Steam, только те предметы, которые Вы еще не выставили на продажу.)
	**_https://market.csgo.com/api/GetInv/?key=[your_secret_key]_**	
		"ui_id" : "new_313007698_188530139" (ui_id — ID для выставления на продажу)
		если есть интересующий ui_id, идем дальше 
_SetPrice_ (Новые предметы выставляются с префиксом "new_" перед [classid]_[instanceid] предмета)
	**https://market.csgo.com/api/SetPrice/new_[classid]_[instanceid]/[price]/?key=[your_secret_key]**
		В нашем случае 
		new_[classid]_[instanceid] = ui_id из метода GetInv
		[price] — сумма в копейках (целое число)

у меня просто реализовано (отдельно) периодический цикл API запросов готовых строк на предметы

**Comment by millworm** [comment]
да я не в этом плане. я в плане какую цену ставить. часто бывает, что цены идут так: 33, 35, 37, 37
как в таком случае выбирать цену

**Comment by 4ikistik** [comment]
Для начала можно просто фиксированную. 
А потом алгоритм прикрутить, т.к. с алгоритмом выставления цены надо будет еще реализовывать изменения цены предмета в реальном времени - это уже огромный кусок. спасибо.
