### ISSUE TITLE
Запрос оффера

### ISSUE THREAD

**Issue by 4ikistik** [millworm/Csgo.tm-Bot#4]
Заметил, что при запросе бота-оффера идут очень часто запросы обновления инвентаря, может быть поместить это дело в timeout? спс

**Comment by 4ikistik** [comment]
при проблеме steam с обновлением инвентаря также насчитал 12 запросов UpdateInventory за секунду, что приводит к частому **bad key**, спс

**Comment by millworm** [comment]
удали в functions вызовы UpdateInvent(key);

**Comment by 4ikistik** [comment]
я так и сделал сразу же, этот пост на будущий апдейт.

**Comment by millworm** [comment]
у меня просто ключи ни разу не удалялись, поэтому не замечал такой проблемы)
