### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by selfmain** [millworm/Csgo.tm-Bot#5]
Как вообще это закомпилить? Первый раз сталкиваюсь с C#, хотел поковыряться, но мозгов не хватает даже запустить бота xD

**Comment by millworm** [comment]
Скачиваешь студию 15 или выше, скачиваешь сам проект бота, скачиваешь проекты, что в описании и подключаешь их. Компилишь. Да, он работает, но интерфейс в виде консоли

**Comment by selfmain** [comment]
Да и так как бы 15 студия, все скачал, обновил NuGet, но компилить оно все равно почему-то не хочет. =C
![1](https://user-images.githubusercontent.com/32557105/32224367-ce68442a-be49-11e7-96b9-d8b8aa622919.jpg)
![default](https://user-images.githubusercontent.com/32557105/32224368-ce86b888-be49-11e7-9f87-673bace43d1b.png)

**Comment by millworm** [comment]
у тебя проблемы с ссылками. открой в проекте MonoTM2 ссылки и исправь все

**Comment by selfmain** [comment]
![image](https://user-images.githubusercontent.com/32557105/32243925-8c40f232-be7f-11e7-86f3-1c928fb9be32.png)
Непонимайн, почему не хочет работать... Можешь указать на ошибку? (про response)

**Comment by millworm** [comment]
все решения надо перестроить. напиши в телеграме, помогу

**Comment by millworm** [comment]
Потерял строчку https://github.com/millworm/SteamToolkit/commit/3255949d03681b8a166432f9137e1f713a9579ca
