### ISSUE TITLE
SteamToolkit+SteamAuth

### ISSUE THREAD

**Issue by 4ikistik** [millworm/Csgo.tm-Bot#7]
Возможно ли запуск бота без ввода кода TwoFactor? Если да, то что надо править?

**Comment by 4ikistik** [comment]
To generate login codes if you already have a Shared Secret, simply instantiate a SteamGuardAccount and set its SharedSecret. Then call SteamGuardAccount.GenerateSteamGuardCode().

To add a mobile authenticator to a user, instantiate a UserLogin instance which will allow you to login to the account. After logging in, instantiate an AuthenticatorLinker and use AuthenticatorLinker.AddAuthenticator() and AuthenticatorLinker.FinalizeAddAuthenticator() to link a new authenticator. After calling AddAuthenticator(), and before calling FinalizeAddAuthenticator(), please save a JSON string of the AuthenticatorLinker.LinkedAccount. This will contain everything you need to generate subsequent codes. Failing to do this will lock you out of your account.

To fetch mobile confirmations, call SteamGuardAccount.FetchConfirmations(). You can then call SteamGuardAccount.AcceptConfirmation and SteamGuardAccount.DenyConfirmation.
# 
Вы можете пошагово описать весь процесс настройки автоматизации? спасибо.

**Comment by 4ikistik** [comment]
помогите:
API отвечает bad key, задача пойти на страницу https://market.csgo.com/botinfo/ и пересоздать ключ, запомнить его в отдельном файле, например key.json и перезапустить бот с новым ключом без требования ввода TwoFactor. 
сложная реализация? спасибо.

**Comment by millworm** [comment]
> Возможно ли запуск бота без ввода кода TwoFactor? Если да, то что надо править?     

можно. в конфиге не заполнить данные от стима
а второе бессмысленно. ограничивай число запросов в секунду

**Comment by 4ikistik** [comment]
все-таки возможно, это реализовано в TradeWorker.cs функц Auth, но это надо ковыряться в SteamToolkit я так понял?
в том то и проблема, что не могу себя ограничить в запросах в сек ;)

**Comment by 4ikistik** [comment]
You should save Account.SteamMachineAuth after the code has been entered and the request has been successful and pass it to DoLogin in future attempts to login. 
This field can be left blank, but if the account is SteamGuard protected it will ask you for a new code every time.
печально :(

**Comment by millworm** [comment]
в чем суть проблемы?
надо принимать шмотки, но без ввода TwoFactor кода?

**Comment by 4ikistik** [comment]
проблемы может быть и нет, но в поздних версиях бот иногда прекращал отдавать предметы (может у меня только так), надо тестить последнюю версию, может быть такого не будет наблюдаться, глядя на переподключение и т.д. полностью перейду на обновленную версию с понедельника, чтобы контролировать процесс работы. спасибо тебе дружище за этот проект. )

**Comment by 4ikistik** [comment]
Изменения в Новый год - это круто). С НГ и Рождеством Христовым.

**Comment by 4ikistik** [comment]
разобрался. всегда собирал сборку с SteamToolKit из старого (FatherFoxxy), вот поэтому и требовало всегда ввод TwoFactor при первом запуске окна.
