### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by 4ikistik** [millworm/Csgo.tm-Bot#8]
решил протестить последнюю сборку -> ошибка подгрузки конфига в файлах CBot.cs значений SteamLogin и SteamPassword и в файле TradeWorker.cs значений SteamLogin, SteamPassword и SteamMachineAuth. Что делаю не так?

пример: Ошибка	CS1061	'Config" не содержит определения для "SteamLogin" и не удалось найти метод расширения "SteamLogin", принимающий тип "Config" в качестве первого аргумента (возможно, пропущена директива using или ссылка на сборку).

**Comment by millworm** [comment]
наверное перед сборкой удалил из Config.cs строки
[c 10 по 13](https://github.com/millworm/Csgo.tm-Bot/blob/master/MonoTM2/Config.cs#L10)

**Comment by 4ikistik** [comment]
собрал, спасибо. когда запускаешь бот с плохим ключом, пустой экран, хотя в предыдущих сборках отписывало, что ключ слетел.
